apiVersion: v1
kind: Secret
metadata:
  name: pixabay-apikey
data:
  API_KEY: bXktc3RyaW5n
  # base64 encoded value should look something like this, note that this won't work
  # create your own apikey if you would like to test the app