apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: project
data:
  PORT: '3000'
  FILES_DIR: /usr/src/app/files
  TODO_API_BASE_URL: http://todo-backend-svc:2345
  IMG_URL: https://picsum.photos/1200
  IMG_FOLDER: files
