apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
  namespace: project
spec:
  # Run every hour at minute 0 (0 * * * *)
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 18  # Keep ~3 hours of successful jobs (18 * 10min)
  failedJobsHistoryLimit: 12 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: todo-generator
        spec:
          restartPolicy: OnFailure
          containers:
          - name: todo-generator
            image: toussyn/gen-todo:v01
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: todo-config
