apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000


---
apiVersion: v1
kind: Service 
metadata:
  name: todo-headless
  namespace: project
spec:
  clusterIP: None
  selector:
    app: todo-sql
  ports:
    - port: 5432
      name: web
