apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: image-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi