apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/volume_claim.yaml
  - manifests/config.yaml
  - manifests/service.yaml
  - manifests/stateful_set.yaml
  - manifests/deployment.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
images:
  - name: IMAGE_WRITER
    newName: placeholder
  - name: TODO_APP
    newName: placeholder
  - name: TODO_BACKEND
    newName: placeholder